### ISSUE TITLE
Site is not responsive

### ISSUE THREAD

**Issue by aamitk** [aamitk/cctv_info#1]

**Comment by gayatrisingh31** [comment]
Hi @aamitk Can i resolve this issue?

**Comment by aamitk** [comment]
Hi @gayatrisingh31 Yes, Go ahead.

**Comment by gayatrisingh31** [comment]
Hi @aamitk I have created PR for this please review it.

**Comment by aamitk** [comment]
Thank you @gayatrisingh31
